export const DevicesActionTypes = {
    FETCH_DEVICES_REQUEST: 'FETCH_DEVICES_REQUEST',
    FETCH_DEVICES_SUCCESS: 'FETCH_DEVICES_SUCCESS',
    FETCH_DEVICES_FAILURE: 'FETCH_DEVICES_FAILURE',
    FETCH_DEVICE_REQUEST: 'FETCH_DEVICE_REQUEST',
    FETCH_DEVICE_SUCCESS: 'FETCH_DEVICE_SUCCESS',
    FETCH_DEVICE_FAILURE: 'FETCH_DEVICE_FAILURE'
}