export const UserActionTypes = {
    AUTH_USER_REQUEST: 'AUTH_USER_REQUEST',
    AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS',
    AUTH_USER_FAILURE: 'AUTH_USER_FAILURE',
    GET_USER_INFO_REQUEST: 'GET_USER_INFO',
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
    GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE'
}